services:
  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vehicles
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Admin para PostgreSQL (opcional)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

  # Redis para cache
  redis:
    image: redis:7
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"

  # RabbitMQ para mensageria
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-broker
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # protocolo AMQP
      - "15672:15672" # painel de admin

  # API-1
  api1:
    build: ../api1
    container_name: api1
    restart: always
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080     # porta dentro do container
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vehicles
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JWT_SECRET: mysecret123
    depends_on:
      - postgres
      - rabbitmq
      - redis

  # API-2
  api2:
    build: ../api2
    container_name: api2
    restart: always
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vehicles
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - rabbitmq
      - redis

volumes:
  pgdata:
