server:
  port: 8081

spring:
  application:
    name: api-1

  datasource:
    url: jdbc:postgresql://localhost:5432/vehicles
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # recriar a estrutura do banco!
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

queue:
  marca:
    name: fila.marcas