server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: api2

  datasource:
    url: jdbc:postgresql://localhost:5432/vehicles
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # para dev: cria/atualiza tabelas automaticamente
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 2.0

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG

---

# perfil ativo
spring:
  profiles:
    active: dev

queue:
  marca:
    name: fila.marcas